# Generated by Django 6.0.7 on 2026-07-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_task_title_per_date',
        ),
    ]
