# Generated by Django 6.0.7 on 2026-08-06 11:36

from django.db import migrations

TAG_NAMES = ['Backend', 'Frontend', 'Design', 'UI', 'Testing']


def create_tags(apps, schema_editor):
    Tag = apps.get_model('task', 'Tag')
    for name in TAG_NAMES:
        Tag.objects.get_or_create(name=name)


def remove_tags(apps, schema_editor):
    """Откат — удаляет те же теги."""
    Tag = apps.get_model('task', 'Tag')
    Tag.objects.filter(name__in=TAG_NAMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_tag_task_priority_task_project_projectfile_task_tags'),
    ]

    operations = [
        migrations.RunPython(create_tags, remove_tags),
    ]

