# Generated by Django 6.0.7 on 2026-08-06 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_seed_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file_path',
            field=models.FileField(max_length=500, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'csv', 'doc', 'docx', 'xlsx'])], verbose_name='File path'),
        ),
    ]
