# Generated by Django 6.0.7 on 2026-09-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_category_deleted_at_category_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_active_category_name'),
        ),
    ]
