# Generated by Django 6.0.7 on 2026-09-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_subtask_owner_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_notified_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('in_progress', 'In progress'), ('pending', 'Pending'), ('blocked', 'Blocked'), ('done', 'Done')], editable=False, max_length=15, verbose_name='Last notified status'),
        ),
    ]
